export default {
  GET_SHORTENED_URL_FROM_SERVER: "GET_SHORTENED_URL_FROM_SERVER",
  SET_SHORTENED_URL: "SET_SHORTENED_URL",
  GET_SHORTENED_URL_LIST: "GET_SHORTENED_URL_LIST",
  SET_SHORTENED_URL_LIST: "SET_SHORTENED_URL_LIST",
  SET_URL_ERROR: "SET_URL_ERROR",
  GET_URL_ERROR: "GET_URL_ERROR"
};
